name: ""
description: ""
inputs:
  name:
    description: "Check packages"
    default: "No name provided"
runs:
  using: "composite"
  steps:
    - run: echo "Deploy backend"
      shell: bash
    - run: npm install
      shell: bash
    - run: npm run build
      shell: bash
