name: ""
description: ""
inputs:
  name:
    description: "Check packages"
    default: "No name provided"
runs:
  using: "composite"
  steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: echo "Deploy backend"
      shell: bash
    - run: npm install
      shell: bash
    - run: npm run build
      shell: bash
