name: "asd"
description: "ads"
inputs:
  name:
    description: "Deploy frontend"
    default: "No name provided"
runs:
  using: "composite"
  steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: echo "Deploy frontend"
      shell: bash
    - run: npm install
      shell: bash
    - run: npm run build
      shell: bash
