name: "asd"
description: "ads"
inputs:
  name:
    description: "Deploy frontend"
    default: "No name provided"
runs:
  using: "composite"
  steps:
    - run: echo "Deploy frontend"
      shell: bash
    - run: npm run install
      shell: bash
    - run: npm run build
      shell: bash
