on:
  workflow_dispatch:
    inputs:
      parameter:
        description: Deploy server
    # branches: [master]
  # push:
  #   branches: [master]
  # pull_request:
  #   branches: [master]
name: Build source
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    env:
      DEMO: 1

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Check env
        run: printenv
          
  deploy-1:
    needs: ['init']
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    env:
      VERSION: 1

    steps:
      - uses: actions/checkout@v2
      - name: Check env
        run: printenv
      - uses: ./.github/actions/install-packages

  deploy-2:
    needs: ['deploy-1']
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Check env
        run: printenv
      - uses: ./.github/actions/build-frontend

