on:
  workflow_dispatch:
    inputs:
      parameter:
        description: Deploy server
    # branches: [master]
  # push:
  #   branches: [master]
  # pull_request:
  #   branches: [master]
name: Build source
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    # defaults:
    #   run:
    #     working-directory: ./frontend
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm cache clean -force
          npm cache verify
          npm update


